### PR TITLE
Update documents in line with ownership transfer

### PR DESCRIPTION
**Pull request by kimikage**
As the repository URL shows, I took over the owner of this repository from @timholy.

On this occasion, I added @darwindarak, the contributor of SVG support, to the copyright owners. (I haven't contributed yet, though.)

Do you have any thoughts on this?

### CODE REVIEW

**Comment by timholy** [comment]
In anticipation of future contributions, you should probably list yourself before me.

**Comment by kimikage** [comment]
I'm requesting to update the repository URL in the General registry.
https://github.com/JuliaRegistries/General/pull/13902

**Review by timholy — APPROVED** [review]

**Comment by PallHaraldsson** [comment]
[EDIT: Ignore, no longer sure.] It seems Tim Holy is modest. <s>I would list him first.</s> Not sure if there's a rule about alphabetical or chronological order, but at least for now, he did most (<s>all?</s>) of the work.

**Comment by kimikage** [comment]
I am asking @darwindarak about the credit. If there is no answer for a while, I will update LICENSE in another PR.

> he did most (all?) of the work.

That's right, but not exactly.
https://github.com/timholy/ProfileView.jl/blob/v0.5.3/src/svgwriter.jl
https://github.com/timholy/ProfileView.jl/blob/v0.5.3/src/viewer.js

My acceptance of @timholy's suggestion (https://github.com/kimikage/ProfileSVG.jl/pull/10#issuecomment-621402639) does never underestimate @timholy's contribution. I am willing to take responsibility for this package until the "more competent maintainer" appears.

BTW, I don't like JavaScript, but it's a matter of taste. At least six years ago, Snap.svg was a state-of-the-art library, and the tricky notation was the best practice when ES6 (ES2015) wasn't available. So, I have no intention of blaming anyone.

**Comment by timholy** [comment]
Thanks for the support, @PallHaraldsson, but truth be told I have not done much here. I essentially accepted @darwindarak's work and did the minimum needed to maintain it. @kimikage's contributions will eclipse my own by, say, next week. Or perhaps later today :smile:.

The git history is very confusing because it was split out from ProfileView. I did make sure that the initial commit credited @darwindarak but it was just a copy/paste of finished code.

**Comment by kimikage** [comment]
The repository URL in the General registry was updated. (cf. JuliaRegistries/General#13902)
If PR #21 is ok, I will merge this PR excluding the LICENSE. And then, I will merge PR #21, #11 and  #12, and release v0.1.1.

**Comment by kimikage** [comment]
I will leave the recommendation of ProfileVega until some bug fixes and improvements are completed.

**Pull request merged**
