### PR TITLE
Bump compat for FlameGraphs + bump version

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by JamesWrigley** [comment]
Hey @kimikage :) Would it be possible to merge this if the tests all pass? It's holding back some other packages downstream.

**Comment by mofeing** [comment]
> Hey @kimikage :) Would it be possible to merge this if the tests all pass? It's holding back some other packages downstream.

This repo looks abandoned. @kimikage has no public commits since 2021.

**Comment by JamesWrigley** [comment]
Indeed, though I was hoping they'd see the notification... @timholy, do you still have access to the repo?

**Comment by JamesWrigley** [comment]
Thanks @kimikage! And sorry that you're not doing so well, I hope you get better soon :heart:

**Pull request merged**
