### PR TITLE
Allow latest version of Colors

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
It's my first PR for version bounds. I just assume this will work as ProfileView allows, a related package. This is not tested, I'm not sure how to best do that, why I didn't add "skip ci". Can we rely on passing Codeconv Report (at least in this case, I know in theory not)?

**Comment by timholy** [comment]
This is good! But if you click on the Travis logs, you'll see something is still keeping it to Colors 0.11.2. So I won't merge this until the tests run with the new version.

**Comment by kimikage** [comment]
I think you need to raise the compat version of FlameGraphs to "0.2".

The current ProfileSVG seems to be compatible with both FlameGraphs v0.1 and v0.2, but I think we should drop support for v0.1 and release ProfileSVG v0.2.0. Of course this policy is only for v0.x series.

I hope this package stays up to date, because ProfileView (Gtk.jl) does not recommend to run it on Windows. However I'm reluctant to be the main maintainer, not one of the contributors. I love SVG but hate JavaScript! :dizzy_face:

**Comment by kimikage** [comment]
cf. #10 
I'm going to fix #9, and then release v0.1.1. After that, 
> The current ProfileSVG seems to be compatible with both FlameGraphs v0.1 and v0.2, but I think we should drop support for v0.1 and release ProfileSVG v0.2.0.

However, releasing v0.2.0 will still take time. We'll pin #master to work around the problem with the compat.

**Comment by PallHaraldsson** [comment]
>I love SVG but hate JavaScript!

I got a 4 MB SVG file, and the web browser had a hard time with it, its task manager showed 656.7 MB for that one tab. I share your JavaScript/web browser hate, but I'm not sure what is to blame here (web browsers are still partly built with JS, I'm just not sure of the rendering part [for SVG]).

[EDIT: for that 23345 line SVG file, I noticed JavaScript appended, two scripts starting at lines 22990 and 23134, so JS may well be to blame, either or both of those. The former (only) seems minimized, but I think such has little effect.]

**Comment by kimikage** [comment]
I have an idea to reduce the SVG file size by ~25% but it won't help in your case. So, I think the feature we need is to reject huge graphs by default. Perhaps the `view()` or `save()` would need more flexibility in handling kwargs in order to implement the feature.


In any case, it's worth submitting a new issue.

**Comment by PallHaraldsson** [comment]
>I think you need to raise the compat version of FlameGraphs to "0.2".

If you mean this for me, then I tried to find a way to add to the patch here, but not obvious (because marked as Draft?).

Do not tag or maintain this package on my account. Since I discovered ProfileView actually does zooming, it's all I need and fast. I just tried this one (by default larger), and seemed like a workaround. I also worked around the package conflict I had for this package.

**Comment by PallHaraldsson** [comment]
The file did actually display for me, just got a "waiting" banner, and I've seen worse, I recall 2 GB for one tab. The size isn't bad for a modern computer (or vs typical JPG), just the CPU time.

**Comment by kimikage** [comment]
> If you mean this for me, then I tried to find a way to add to the patch here, but not obvious (because marked as Draft?).

I'm sorry to change this to Draft PR. My intention is that I don't want to support both FlameGraphs v0.1 and v0.2 at the same time. So, I want to commit the fixes without major breaking changes, first.

However, that is just my opinion, not a definite decision. 

> The size isn't bad for a modern computer (or vs typical JPG), just the CPU time.

In SVG, the DOM tree manipulation rather than the rendering is likely to be a bottleneck. This is a trade-off with the benefits of SVG.

**Comment by kimikage** [comment]
I am sorry I kept you waiting. We can at length merge this.

Probably not able to handle 4 MB of profile data yet, but it should have improved performance slightly.

Let's start the v0.2 series.

**Edit:**
You can use Colors v0.12 with `pkg> add ProfileSVG#master`.

**Pull request merged**
